### PR TITLE
strong-mode

### PR DESCRIPTION
**Pull request by lejard-h**
fix for strong mode and ddc

### CODE REVIEW

**Comment by lejard-h** [comment]
it was fast thanks :+1:

**Comment by lejard-h** [comment]
Hey @sethladd , any idea when you will release it on pub ?

**Comment by sethladd** [comment]
Actually, do you want to take ownership of this project? I no longer use it. I'll be happy to transfer to you (or another motivated owner :)

**Comment by lejard-h** [comment]
Why not :)

**Comment by sethladd** [comment]
OK, I'll send it over to you :)

**Comment by sethladd** [comment]
Hm, can you rename your fork? I can't transfer to you because lawndart already exists for you.

**Comment by sethladd** [comment]
Actually, looks like you need to delete your fork before I can transfer.

**Comment by lejard-h** [comment]
I deleted it

**Pull request merged**
